### ISSUE TITLE
New entity to represent an "External Link"

### ISSUE THREAD

**Issue by thechriswalker** [arago/OGIT#188]
I have a need for an entity to represent an external URL. The use-case is that an `ogit/Forum/Post` can have references to other entities, such as `ogit/Automation/KnowledgeItem`s or `ogit/Forum/Profile`s, however they could reference an abitrary URL and having this as an entity with the same verb connecting in to the post would be good. I am thinking something like:

```yaml
- Entity:
    id: http://www.purl.org/ogit/Hyperlink
    name: Hyperlink
    description: |
      A representation of an (optionally) titled Hyperlink to some media. No protocol restrictions imposed.
    valid-from: 2015-06-09
    valid-until:
    creator: cwalker@arago.de
    deleter:
    created: 2015-06-09
    modified: 2015-06-09
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    scope: SGO
    parent: http://www.purl.org/ogit/Node
    attributes:
      mandatory:
        - http://www.purl.org/ogit/url
      optional:
        - http://www.purl.org/ogit/title
    history:
      - id: 1
        date: 2015-05-21
        description: initial
        modified-by: cwalker@arago.de
```

I suggest the SGO as this is a very generic type as presented, or we could make it more specific as a `ogit/Forum/ExternalLink` entity, I am not sure.

I had also envisaged `ogit/connects` for the verb between the link and the post.

Any comments before I include in a pull request?
