### ISSUE TITLE
New Entity/Verbs for Invite and Permission

### ISSUE THREAD

**Issue by brendanmoore** [arago/OGIT#200]
TabTab needs an entity that represents a user being invited to participate in a private group/topic. The Invite will `ogit/correspond` to a `ogit/Forum/Topic` and a `ogit/Forum/Profile` can choose to accept `ogit/accepts` or reject `ogit/rejects` the invite: 

Here is what I propose.

## New Enitities
```yaml
- Entity:
    id: http://www.purl.org/ogit/Forum/Invite
    name: Invite
    description: Invite is used to request participation with a node
    creator: bmoore@arago.de
    deleter:
    created: 2015-09-02
    modified: 2015-09-02
    valid-from: 2015-09-02
    valid-until:
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    scope: NTO
    parent: http://www.purl.org/ogit/Node
    history:
      - id: 1
        date: 2015-09-02
        description: Initial Creation
        modified-by: bmoore@arago.de

    attributes:
      mandatory:
        - http://www.purl.org/ogit/token
      optional:

```
## New verbs
```yaml
- Verb:
    id: http://www.purl.org/ogit/accepts
    name: accepts
    description: |
      Indicates if an entity accepts something else.
    valid-from: 2015-09-02
    valid-until:
    creator: bmoore@arago.de
    deleter:
    created: 2015-09-02
    modified: 2015-09-02
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    cardinality:
    allowed:
      - from: http://www.purl.org/ogit/Forum/Profile
        to: http://www.purl.org/ogit/Forum/Invite
    history:
      - id: 1
        date: 2015-09-02
        description: initial
        modified-by: bmoore@arago.de
```

```yaml
- Verb:
    id: http://www.purl.org/ogit/rejects
    name: rejects
    description: |
      Indicates if an entity rejects something else.
    valid-from: 2015-09-02
    valid-until:
    creator: bmoore@arago.de
    deleter:
    created: 2015-09-02
    modified: 2015-09-02
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    cardinality:
    allowed:
      - from: http://www.purl.org/ogit/Forum/Profile
        to: http://www.purl.org/ogit/Forum/Invite
    history:
      - id: 1
        date: 2015-09-02
        description: initial
        modified-by: bmoore@arago.de
```

**Comment by brendanmoore** [comment]
Also there is a requirement for a  `Permission` entity which is used at an application level to determine which node (Profile/Organisation) can interact with another node (Topic/Post/Comment...)
## New Entity
```yaml
- Entity:
    id: http://www.purl.org/ogit/Forum/Permission
    name: Permission
    description: Permission is used to approve a Nodes interaction with another Node
    creator: bmoore@arago.de
    deleter:
    created: 2015-09-04
    modified: 2015-09-04
    valid-from: 2015-09-04
    valid-until:
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    scope: NTO
    parent: http://www.purl.org/ogit/Node
    history:
      - id: 1
        date: 2015-09-04
        description: Initial Creation
        modified-by: bmoore@arago.de

    attributes:
      mandatory:
      optional:

```
