### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by thechriswalker** [arago/OGIT#213]
When the `versioning.yaml` file is updated, I think we should create a Tag in the repository with the same version.

The hope is that only these tagged commits get deployed to GraphIT and this way, when I see that graphit is running `2.9.0` I can simply checkout 2.9.0 and know that I have the **exact same ontology** my target database is using. Without this, I am completely in the dark as to the actual ontology on a given GraphIT server.

Thoughts?

**Comment by thechriswalker** [comment]
@p1tz I think we have spoken about this before - I would appreciate your thoughts.

**Comment by p1tz** [comment]
yes please!

**Comment by brendanmoore** [comment]
Helpful resource: https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by thechriswalker** [comment]
Also, the `versioning/version.yaml` is badly formed. It parses ok, but the history is always lost due to the key being overwritten! e.g.

```yaml
- Ontology:
  version: 2.10.0
  history:
    - id: one
      desc: description one
  history:
    - id: two
      desc: description two
```

Is actual equivalent to:

```yaml
- Ontology:
  version: 2.10.0
  history:
    - id: two
      desc: description two
```

when I think we actually want:

```yaml
- Ontology:
  version: 2.10.0
  history:
    - id: one
      desc: description one
    - id: two
      desc: description two
```

I am happy to make the change and pull request, but I am not sure if this *feature/bug* will affect GraphIT if amended. Can you clarify @p1tz?
